### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by nriqu322**
- Added players class
- Added board class
- Game flow improved

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @nriqu322, @voscarmv, good work here :+1:. Just a few requirements are left :fast_forward:**
1. Remove all inline comments from your code.
2. Your main.rb is not executable. What you should have on the first line is `#!/usr/bin/env ruby` and not `#!/usr/bin/env ruby is the top line`.
3. In the game loop, since we are repeating the same actions in the players's turns, let us factor out the actions into a method and call the action for each player instead of repeating the same code over again.





**Optional:** You can factor out the `return true if ....` lines (in the board check_symbol_victory method) into a method that takes a sub_arr and the symbol.

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by voscarmv** [comment]
Thanks for your review @mosesogwo , I'll implement your recommendations and let you know when I'm done.

**Comment by voscarmv** [comment]
@mosesogwo done. I just requested a new code review.

**Comment by mosesogwo** [comment]
> @mosesogwo done. I just requested a new code review
Okay. Another reviewer will take a look at it soon. Regards.

**Review by MauricioRobayo — APPROVED** [review]
Nice UI and well done keeping the score. 

The project looks great and all requirements from the previous review are addressed.

Status: __Approved__.

**Pull request merged**
